e_commerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pedido/', include('pedido.urls')),
    # define o caminho(pedido?) das URL e inclue(include('pedido.urls')) elas de um arquivo especifico.
    path('perfil/', include('perfil.urls')),
    path('', include('produto.urls')),


]


if settings.DEBUG:  # interagem com as URL das imagens
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pedido/urls.py
from django.urls import path
from . import views

app_name = 'pedido' # Define o namespace  do aplicativo para envitar conflitos de nomeclatura

urlpatterns = [
    path('pagar/<int:pk>', views.Pagar.as_view(), name='pagar'),
    path('salvarpedido/', views.SalvarPedido.as_view(), name='salvarpedido'),
    path('lista/', views.Lista.as_view(), name='lista'),
    path('detalhe/<int:pk>', views.Detalhe.as_view(), name='detalhe'),
]


"""
 "pk" Abreviação de chave primaria(Primary Key) é um valor único associado a cada registro no baco de dados

<int:pk>
    Significa que a URL espera um parâmetro chamdo"pk" que deve ser um número inteiro(int). 
    Parametro geralmente usado para identificar de forma exclusiva um objeto específico do BD
"""

perfil/urls.py
from django.urls import path
from . import views

app_name = 'perfil'

urlpatterns = [
    path('', views.Criar.as_view(), name='criar'),
    path('atualizar/', views.Atualizar.as_view(), name='atualizar'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

produto/urls.py
from django.urls import path
from . import views

app_name = 'produto' # Nome da aplição

urlpatterns = [ # Mapeamento de URls
    
    path('', views.ListaProdutos.as_view(), name="lista"),
    path('<slug>', views.DetalheProduto.as_view(), name="detalhe"),
    path('adicionaraocarrinho/', views.AdicionarAoCarrinho.as_view(),
         name="adicionaraocarrinho"),
    path('removerdocarrinho/', views.RemoverDoCarrinho.as_view(),
         name="removerdocarrinho"),
    path('carrinho/', views.Carrinho.as_view(), name="carrinho"),
    path('resumodacompra/', views.ResumoDaCompra.as_view(), name="resumodacompra"),
    path('busca/', views.Busca.as_view(), name="busca"),
]

produto/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.utils.html import mark_safe
from utils.f_produto import formata_preco
from PIL import Image
import os


class Produto(models.Model):
# Modelo com objetivo de resgistrar produtos da tabela
    name           = models.CharField(max_length = 255) 
    des_curta      = models.TextField(max_length = 255)
    des_longa      = models.TextField()
    imagem         = models.ImageField(upload_to = 'Produto_image/%y/%m/', 
                                       blank = True, null = True)
    # Variavel de um campo que armazenara imagens, em um  diretorio nomeado(upload_to).
    slug           = models.SlugField(unique = True, 
                                      blank = True, null = True  ) # URL ddo produto
    pre_marke      = models.FloatField()
    pre_marke_prom = models.FloatField(default = 0)
    tipo           = models.CharField(default = 'v',max_length = 1,choices =(
                                        ('V', 'Variavel'),('S', 'Simples' ),))
    # Forneçera duas opções(choice) com uma sendo ja pré definida(Default) e com o quantidade especifica(max_length)
    
    def image_tag_path(self): # Define o tamanho da imagem ná área admin 
        return mark_safe('<img src= "%s" width="100" height="80"/>' % (self.imagem.url))
    
    def get_preco_formatado(self):    
        return formata_preco(self.pre_marke) # Função da pasta utils.f_produtos
    get_preco_formatado.short_description = 'preço'

    def get_preco_formatado_promo(self):    
        return formata_preco(self.pre_marke_prom) # Função da pasta utils.f_produtos
    get_preco_formatado_promo.short_description = 'preço promo'


    @staticmethod
    def resize_image(img, new_width=800):
    # Função que realiza a redimensão da imagem escolhida(img) para o produto, definido uma largura padrão(new_width)
        img_full_path = os.path.join(settings.MEDIA_ROOT, img.name) # Caminho da imagem
        img_pil       = Image.open(img_full_path) # abre a imagem      
        original_width, original_height = img_pil.size

        if original_width <= new_width:
            # Se a imagem original for menor ou igual a largura definida(new_width) não ouvera alteração
            img_pil.close()    
            return
        
        new_height = round((new_width * original_height) / original_width)
        # Calcula a nova altura da imagem usando regra de 3 
        new_img    = img_pil.resize((new_width, new_height), Image.LANCZOS)
        # raliza a redimensão da imagem por meio de um calculo matematico(LANCZOS) 
        new_img.save(img_full_path, optimize=True, quality=50)
        # Realizando o salvamento(save) da nova imagem encima da antiga.


    
    def save(self, *args, **kwargs):
    # cria slug para o produto a partir do nome se o slug estiver vazio
    # além de redimencionar a imagem do produto 
        
        # verifica se o campo do slug está vazio
        if not self.slug:
            # Cria um slug(slugify) a partir do nome do produto
            slug      = f'{slugify(self.name)}'
            self.slug = slug

        super().save(*args, **kwargs) # Salva o slug criado na base de dados

        max_image_size = 800 # Define o tamanho máximo da imagem

        # Redimendiona a imagem se existir
        if self.imagem:
            self.resize_image(self.imagem, max_image_size)

    def __str__(self): # mostra o nome do produto na área admin
        return self.name

class Variacao(models.Model):
    # Modelo com o objetivo de registrar varações do mesmo produto, 
    # esta ligada diretamente ao modelo produto.
    produto  = models.ForeignKey(Produto, on_delete=models.CASCADE)
    # Chave estrangeira(ForeignKey) relacionada ao modelo produto(produto).
    nome     = models.CharField(max_length=50, blank=True, null=True)
    preco    = models.FloatField()
    pre_prom = models.FloatField(default=0)
    estoque  = models.PositiveIntegerField(default=1)
    # Sempre tera que aver  pelomenos 1 produto(deafault) 

    def __str__(self):
        return self.nome or self.produto.nome
    
    def get_v_preco_formatado(self):    
        return formata_preco(self.preco) # Função da pasta utils.f_produtos
    get_v_preco_formatado.short_description = 'preço'

    def get_v_preco_formatado_promo(self):    
        return formata_preco(self.pre_prom) # Função da pasta utils.f_produtos
    get_v_preco_formatado_promo.short_description = 'preço promo'

    class Meta:
        # realisa a mundaça do nome da classe dentro da area de admin
        verbose_name        = 'Variação'
        verbose_name_plural = 'Variações'

produto/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views import View
from django.contrib import messages
from django.db.models import Q
from . import models
from perfil.models import Perfil

class ListaProdutos(ListView):
    #classe de visualização baseada em django para exibir uma lista de produtos.
    model = models.Produto 
    template_name = 'produto/lista.html' 
    context_object_name = 'produtos' 
    paginate_by = 6 
    ordering = ['-id']
    
class DetalheProduto(DetailView):
    #classe de visualização baseada em django para exibir os detalhes de um produto especifico.
    model = models.Produto  
    template_name = 'produto/detalhe.html'
    context_object_name = 'produto'
    slug_url_kwarg = 'slug' # Especifica o nome do argumento da URL que será usado para recuperar o objeto do modelo

class AdicionarAoCarrinho(View):
    # Classe de visualização no Django baseada em função para adicionar produtos ao carrinho

    def get(self, *args, **kwargs):
        # Método GET para processar a adição de produtos ao carrinho

        # Obtém a URL de referência da solicitação
        http_referer = self.request.META.get(
            'HTTP_REFERER',
            reverse('produto:lista')
        )
        
        # Obtém o ID da variação do produto da solicitação GET
        variacao_id = self.request.GET.get('vid')

        # Verifica se o ID da variação existe
        if not variacao_id:
            messages.error(
                self.request,
                'Não há esse produto no estoque'
            )
            return redirect(http_referer)

        # Obtém a variação do produto com base no ID
        variacao = get_object_or_404(models.Variacao, id=variacao_id)
        variacao_estoque = variacao.estoque
        produto = variacao.produto

        # Atribui valores às variáveis para facilitar o acesso
        produto_id = produto.id
        produto_nome = produto.name
        variacao_nome = variacao.nome or ''
        preco_unitario = variacao.preco
        preco_unitario_promocional = variacao.pre_prom
        quantidade = 1
        slug = produto.slug
        imagem = produto.imagem

        # Verifica se há imagem e atribui o nome da imagem
        if imagem:
            imagem = imagem.name
        else:
            imagem = ''

        # Verifica se o estoque da variação é suficiente
        if variacao.estoque < 1:
            messages.error(
                self.request,
                'Estoque insuficiente'
            )
            return redirect(http_referer)

        # Verifica se a sessão do carrinho existe
        if not self.request.session.get('carrinho'):
            self.request.session['carrinho'] = {}
            self.request.session.save()

        # Obtém o carrinho da sessão
        carrinho = self.request.session['carrinho']

        # Verifica se a variação já está no carrinho
        if variacao_id in carrinho:
            quantidade_carrinho = carrinho[variacao_id]['quantidade']
            quantidade_carrinho += 1

            # Verifica se o estoque é suficiente para a quantidade desejada
            if variacao_estoque < quantidade_carrinho:
                messages.warning(
                    self.request,
                    f'Estoque insuficiente para {quantidade_carrinho}x no '
                    f'produto "{produto_nome}". Adicionamos {variacao_estoque}x '
                    f'no seu carrinho.'
                )
                quantidade_carrinho = variacao_estoque

            # Atualiza as informações no carrinho
            carrinho[variacao_id]['quantidade'] = quantidade_carrinho
            carrinho[variacao_id]['preco_quantitativo'] = preco_unitario * quantidade_carrinho
            carrinho[variacao_id]['preco_quantitativo_promocional'] = preco_unitario_promocional * quantidade_carrinho
        else:
            # Adiciona uma nova entrada ao carrinho
            carrinho[variacao_id] = {
                'produto_id': produto_id,
                'produto_nome': produto_nome,
                'variacao_nome': variacao_nome,
                'variacao_id': variacao_id,
                'preco_unitario': preco_unitario,
                'preco_unitario_promocional': preco_unitario_promocional,
                'preco_quantitativo': preco_unitario,
                'preco_quantitativo_promocional': preco_unitario_promocional,
                'quantidade': 1,
                'slug': slug,
                'imagem': imagem,
            }

        # Salva a sessão do carrinho
        self.request.session.save()

        # Exibe mensagem de sucesso
        messages.success(
            self.request,
            f'Produto {variacao_nome} adicionado ao seu '
            f'carrinho {carrinho[variacao_id]["quantidade"]}x.'
        )

        # Redireciona de volta à página de referência
        return redirect(http_referer)


class RemoverDoCarrinho(View):
     def get(self, *args, **kwargs):
        http_referer = self.request.META.get(
            'HTTP_REFERER',
            reverse('produto:lista')
        )
        variacao_id = self.request.GET.get('vid')

        if not variacao_id:
            return redirect(http_referer)

        if not self.request.session.get('carrinho'):
            return redirect(http_referer)

        if variacao_id not in self.request.session['carrinho']:
            return redirect(http_referer)

        carrinho = self.request.session['carrinho'][variacao_id]

        messages.success(
            self.request,
            f'Produto {carrinho["variacao_nome"]} '
            f'removido do seu carrinho.'
        )

        del self.request.session['carrinho'][variacao_id]
        self.request.session.save()
        return redirect(http_referer)

class Carrinho(View):
    def get(self, *args, **kwargs):
        contexto = {
            'carrinho':self.request.session.get('carrinho', {})
        }
        return render(self.request, 'produto/carrinho.html' ,contexto)

class ResumoDaCompra(View):
    def get(self, *args, **kwargs):

        if not self.request.user.is_authenticated:
            return redirect('perfil:criar')


        contexto = {
            'usuario' : self.request.user,
            'carrinho' : self.request.session['carrinho'],
        }
        
        perfil = Perfil.objects.filter(usuario = self.request.user).exists()

        if not perfil:
            messages.error(
                self.request,
                'Usuario sem perfil.'
            )

        if not self.request.session.get('carrinho'):
            messages.error(
                self.request,
                'Carrinho vazio.'
            )

        return render(self.request, 'produto/resumodacompra.html', contexto)

class Busca(ListaProdutos):
    def get_queryset(self, *args, **kwargs):
        termo = self.request.GET.get('termo') or self.request.session['termo']
        qs = super().get_queryset(*args, **kwargs)

        if not termo:
            return qs

        self.request.session['termo'] = termo

        qs = qs.filter(
            Q(name__icontains=termo) |
            Q(des_curta__icontains=termo) |
            Q(des_longa__icontains=termo)
        )

        self.request.session.save()
        return qs

produto/templates/produto/carrinho.html
{% extends 'base.html' %}
{% load omfilters %}

{% block titulo %}Carrinho | {% endblock %}

{% block conteudo %}

{% if carrinho %}

<div class="row mt-3">
    <div class="col">
        <h3>Carrinho de compras</h3>
        <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>

        {% include 'parciais/_carrinho.html' %}
    </div>
</div>



<div class="row mt-3">
    <div class="col-lg">
        <p class='lead'>Total no carrinho</p>

        <div class='table-responsive'>
            <table class="table">
                <tr>
                    <td class="font-weight-bold">Total</td>
                    <td>{{ carrinho|cart_totals|preco_formatado }}</td>
                </tr>
            </table>
        </div>
    </div>
    <div class="col-lg mt-auto">

        {% if request.user.is_authenticated %}
        <a class="btn btn-lg btn-block btn-primary" href="{% url 'produto:resumodacompra' %}">
            Comprar
        </a>
        {% else %}
        <a class="btn btn-lg btn-block btn-primary" href="{% url 'perfil:criar' %}">
            Entrar ou cadastrar
            {% endif %}
    </div>
</div>

{% else %}

<div class="row mt-3">
    <div class="col">
        <h3>Carrinho vazio</h3>
        <p class="lead">Não há produtos no seu carrinho.</p>
    </div>
</div>

{% endif %}




{% endblock %}

produto/templates/produto/detalhe.html
{% extends 'base.html' %}
{% load omfilters %}

{% block titulo %}{{ produto.name }} | {% endblock %}

{% block conteudo %}
<div class="row">
    <div class="col-lg">
        <div class="row no-gutters">
            <div class="col-lg-12">
                {% if produto.imagem %}
                <img class="img-fluid" src="{{ produto.imagem.url }}">
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-lg">
        <div class="mt-4 mt-lg-0">
            <h1 class="h2">{{ produto.name }}</h1>
            <p class="lead">{{ produto.des_curta }}</p>
            <p class="lead">
                {% if produto.pre_marke_prom %}
                <span id="variation-preco-promocional" class="lead product-price">
                    {{ produto.pre_marke_prom|preco_formatado }}
                </span>
                <span id="variation-preco" class="lead product-old-price text-muted">
                    {{ produto.pre_marke|preco_formatado }}
                </span>
                {% else %}
                <span id="variation-preco" class="lead product-price">
                    {{ produto.pre_marke|preco_formatado }}
                </span>
                {% endif %}
            </p>

            <form action="{% url 'produto:adicionaraocarrinho' %}" id="form-add-to-cart">
                {% if produto.variacao_set.all %}
                <div class="form-group">
                    <select id="select-variacoes" name="vid" class="form-control form-control-lg">
                        {% for variacao in produto.variacao_set.all %}

                        {% if variacao.pre_prom %}
                        <option data-preco="{{ variacao.preco|preco_formatado }}"
                            data-preco-promocional="{{ variacao.pre_prom|preco_formatado }}" value="{{ variacao.id }}">
                            {% if variacao.nome %}
                            {{ variacao.nome }}
                            {% else %}
                            {{ variacao }}
                            {% endif %}
                        </option>
                        {% else %}
                        <option data-preco="{{ variacao.preco|preco_formatado }}" value="{{ variacao.id }}">
                            {% if variacao.nome %}
                            {{ variacao.nome }}
                            {% else %}
                            {{ variacao }}
                            {% endif %}
                        </option>
                        {% endif %}

                        {% endfor %}
                    </select>

                </div>
                {% endif %}

                <div class="text-left">
                    <button type="submit" class="btn btn-primary btn-lg btn-block">
                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                        Adicionar ao carrinho
                    </button>
                </div>

            </form>


        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="mt-5 mb-5">
            <h2 class="text-center">{{ produto.name }}</h2>
            {{ produto.des_longa|linebreaks }}
        </div>
    </div>
</div>


{% endblock %}

produto/templates/produto/lista.html
{% extends 'base.html' %}
{% load omfilters %}

{% block titulo %}Produtos | {% endblock %}

{% block conteudo %}


<h3 class="my-4 boder-bottom pb-1">Produtos</h3>

<div class="row">
    <div class="col-lg-12">
        <div class="card-columns">

            {% for produto in produtos %}

            <div class="card shadow" style="width: 330px; border: 2px solid #CD853F; border-radius: 10px;">

                {% if produto.imagem %}
                <a href="{% url 'produto:detalhe' produto.slug %}">
                    <img class="card-img-top" src="{{ produto.imagem.url }}" alt="{{ produto.name }}"
                        style="height: 250px; border-radius: 8px;">
                </a>
                {% endif %}

                <div class="card-body">
                    <h5 class="card-title">{{ produto.name }}</h5>
                    <p class="card-text">{{ produto.des_curta }}</p>
                    <div class="container product-price-block text-center">

                        {% if produto.pre_marke_prom %}
                        <span class="product-price">
                            {{ produto.pre_marke_prom|preco_formatado }}
                        </span>
                        <span class="product-old-price text-muted">
                            {{ produto.pre_marke|preco_formatado }}
                        </span>
                        {% else %}
                        <span class="product-price">
                            {{ produto.pre_marke|preco_formatado }}
                        </span>
                        {% endif %}

                    </div>
                </div>
                <div class="card-footer bg-transparent border-top-light-custom text-center">
                    <a href="{% url 'produto:detalhe' produto.slug %}" class="btn btn-sm m-1 btn-block"
                        style="background-color: #CD853F; border-color: #CD853F;">
                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                        Comprar
                    </a>
                </div>
            </div>

            {% endfor %}

        </div>
    </div>
</div>

<div class="row mt-3">
    <div class="col">
        {% include 'parciais/_pagination.html' %}
    </div>
</div>

{% endblock %}

produto/templates/produto/resumodacompra.html
{% extends 'base.html' %}
{% load omfilters %}

{% block titulo %}Resumo da compra | {% endblock %}

{% block conteudo %}

<div class="row mb-5">
    <div class="col-lg">
        <h2>Resumo da sua compra</h2>

        <p class="lead">Dados do usuário</p>
        <p>Caso precise editar, <a href="{% url 'perfil:criar' %}">clique aqui</a></p>
        <dl class="row">
            <dt class="col-lg-2">Nome:</dt>
            <dd class="col-lg-4">{{ usuario.first_name }}</dd>
            <dt class="col-lg-2">Sobrenome:</dt>
            <dd class="col-lg-4">{{ usuario.last_name }}</dd>

            <dt class="col-lg-2">Idade:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.idade }}</dd>
            <dt class="col-lg-2">Nascimento:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.data_nasc}}</dd>

            <dt class="col-lg-2">CPF:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.cpf }}</dd>
            <dt class="col-lg-2">E-mail:</dt>
            <dd class="col-lg-4">{{ usuario.email }}</dd>
        </dl>

        <p class="lead">Dados de endereço</p>
        <p>Caso precise editar, <a href="{% url 'perfil:criar' %}">clique aqui</a></p>
        <dl class="row">
            <dt class="col-lg-2">Endereço:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.endereco }}</dd>
            <dt class="col-lg-2">Número:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.numero }}</dd>

            <dt class="col-lg-2">Complemento:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.complemento }}</dd>
            <dt class="col-lg-2">bairro:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.bairro }}</dd>

            <dt class="col-lg-2">Cidade:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.cidade }}</dd>
            <dt class="col-lg-2">Estado:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.estado }}</dd>

            <dt class="col-lg-2">CEP:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.cep }}</dd>
        </dl>
    </div>
</div>



<div class="row mt-3">
    <div class="col">
        <h3>Resumo do carrinho</h3>
        <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>

        {% include 'parciais/_carrinho.html' %}
    </div>

</div>
<div class="row mt-3">
    <div class="col">
        <p class="lead text-center"><span class="font-weight-bold">Total do carrinho:</span>
            {{ carrinho|cart_totals|preco_formatado }}</p>
    </div>
</div>

<div class="row">
    <div class="col">
        <a class="btn btn-block" style="background-color: #CD853F;" href="{% url 'pedido:salvarpedido' %}">
            Realizar pagamento
        </a>
    </div>
</div>


{% endblock %}